services:
  web:
    build: .
    container_name: rakshanridge-web

    working_dir: /app
    command: bash

    stdin_open: true
    tty: true

    ports:
      - "3000:3000"

    volumes:
      - .:/app:Z
      - pnpm-store:/pnpm/store

    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_TELEMETRY_DISABLED: "1"

volumes:
  pnpm-store:
    name: pnpm-store-global
