import { defineType, defineField } from 'sanity'

export const experience = defineType({
    name: 'experience',
    title: 'Experience',
    type: 'document',
    groups: [
        { name: 'content', title: 'Content', default: true },
        { name: 'story', title: 'Story' },
        { name: 'media', title: 'Media' },
    ],
    fields: [
        defineField({
            name: 'title',
            title: 'Title',
            type: 'localeString',
            group: 'content',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            options: { source: 'title.en', maxLength: 96 },
            group: 'content',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'description',
            title: 'Description',
            description: 'Short description shown on cards (grid, room page curated section).',
            type: 'localeText',
            group: 'content',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'duration',
            title: 'Duration',
            description: 'e.g. "Half Day", "Full Day".',
            type: 'localeString',
            group: 'content',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'location',
            title: 'Location',
            description: 'e.g. "Hill Country", "Southern Coast".',
            type: 'localeString',
            group: 'content',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'highlights',
            title: 'Highlights',
            description: 'Bullet list shown under "What\'s Included" on the detail page.',
            type: 'array',
            of: [{ type: 'localeString' }],
            group: 'content',
            validation: (Rule) => Rule.required().min(1),
        }),
        defineField({
            name: 'featured',
            title: 'Featured',
            description: 'Featured experiences are eligible to show on the homepage.',
            type: 'boolean',
            initialValue: false,
            group: 'content',
        }),
        defineField({
            name: 'storyOpening',
            title: 'Story — Opening',
            type: 'localeText',
            group: 'story',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'storyQuote',
            title: 'Story — Pull Quote',
            type: 'localeString',
            group: 'story',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'storyClosing',
            title: 'Story — Closing',
            type: 'localeText',
            group: 'story',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'image',
            title: 'Card image',
            description: 'Used on grid/card layouts (experiences listing, room page curated section).',
            type: 'image',
            options: { hotspot: true },
            group: 'media',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'detailImage',
            title: 'Detail hero image',
            description: 'Used as the hero on the experience detail page.',
            type: 'image',
            options: { hotspot: true },
            group: 'media',
            validation: (Rule) => Rule.required(),
        }),
    ],
    preview: {
        select: { title: 'title.en', subtitle: 'location.en', media: 'image' },
    },
})